"""empty message

Revision ID: 233e9028a5bf
Revises: 
Create Date: 2023-08-08 09:28:01.145783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e9028a5bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('date_survey_completed', sa.DateTime(), nullable=True),
    sa.Column('payment', sa.Numeric(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('date_fg_completed', sa.DateTime(), nullable=True),
    sa.Column('payment_received', sa.Boolean(), nullable=False),
    sa.Column('payment_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('payment_left', sa.Numeric(), nullable=True),
    sa.Column('last_four', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    # ### end Alembic commands ###
