"""makes sure date_fg_completed is nullable

Revision ID: 36597d952457
Revises: 6b49e2fea470
Create Date: 2023-07-31 12:54:07.015917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36597d952457'
down_revision = '6b49e2fea470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'date_fg_completed',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'date_fg_completed',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
