"""empty message

Revision ID: 8cd25a358a2b
Revises: 3b2735b3ccc8
Create Date: 2023-08-07 11:19:10.431430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd25a358a2b'
down_revision = '3b2735b3ccc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('survey', 'survey_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('survey_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('survey', 'id')
    # ### end Alembic commands ###
