"""empty message

Revision ID: 9fed45fe032f
Revises: 
Create Date: 2023-08-07 20:49:01.272532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fed45fe032f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('last_four', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('date_survey_completed', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('date_fg_completed', sa.DateTime(), nullable=True),
    sa.Column('payment_received', sa.Boolean(), nullable=False),
    sa.Column('payment_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('payment_left', sa.Numeric(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    op.drop_table('payment')
    # ### end Alembic commands ###
