"""Adds Survey model

Revision ID: b8a8a883104f
Revises: 
Create Date: 2023-07-25 10:16:54.981002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a8a883104f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=False),
    sa.Column('compensation', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('payment_received', sa.Boolean(), nullable=False),
    sa.Column('payment_expiration_date', sa.Date(), nullable=True),
    sa.Column('payment_left', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('survey_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey')
    # ### end Alembic commands ###
