"""empty message

Revision ID: c3a2017ba24f
Revises: 36597d952457
Create Date: 2023-08-01 10:06:02.809649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a2017ba24f'
down_revision = '36597d952457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('testing', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'testing')
    # ### end Alembic commands ###
